name: dpt-demo
on: 
    push:
        branches: [main]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    -   name: Checkout Repository
        uses: actions/checkout@v4
    -   name: install java
        uses: actions/setup-java@v4
        with: 
            java-version: '11'
            distribution: 'temurin'
    -   name: Cache dependencies
        uses: actions/cache@v3
        with:
            path: |
             ~/.m2
             key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
              restore-keys: |
             ${{ runner.os }}-maven-
                
    -   name: Build with Maven
        run: mvn clean install
    
    -   name: Run Tests
        run: mvn test

## Pushing in to Docker Hub


    -   name: Setting up Docker
        uses: docker/setup-buildx-action@v3

    -   name: Logging in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_UN }}
          password: ${{ secrets.DOCKER_PD }}

    -   name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: mareh786/dptweb-app:latest